variables:
  CXX: "g++ -std=c++17 -O3 -march=native -Wall -Wextra -Icpprb -pthread"
  GIT_SUBMODULE_STRATEGY: recursive

.job_template: &setup
  image: registry.gitlab.com/ymd_h/cpprb/build:latest
  before_script:
    - g++ --version
    - python3 --version

stages:
  - page_export
  - page_deploy
  - cpp_test
  - py_build
  - py_test

ReplayBuffer.cpp:
  <<: *setup
  stage: cpp_test
  script:
    - $CXX -o test/ReplayBuffer test/ReplayBuffer.cpp
    - test/ReplayBuffer
  when: always

SegmentTree.cpp:
  <<: *setup
  stage: cpp_test
  script:
    - $CXX -o test/SegmentTree test/SegmentTree.cpp
    - test/SegmentTree
  when: always

py_build:
  <<: *setup
  stage: py_build
  script:
    - CC=g++ python3 setup.py build_ext
  artifacts:
    paths:
      - build

ReplayBuffer:
  <<: *setup
  stage: py_test
  script:
    - python3 setup.py install
    - cd test
    - python3 PyReplayBuffer.py

issue39:
  <<: *setup
  stage: py_test
  script:
    - python3 setup.py install
    - cd test
    - python3 issue39.py

issue40:
  <<: *setup
  stage: py_test
  script:
    - python3 setup.py install
    - cd test
    - python3 issue40.py

emacs:
  image: iquiw/alpine-emacs
  stage: page_export
  script:
    - emacs --version
    - emacs --batch README.org -l site/init.el --eval '(org-hugo-export-wim-to-md :all-subtrees nil t)'
    - cd site
    - emacs --batch site.org -l init.el --eval '(org-hugo-export-wim-to-md :all-subtrees nil t)'
    - ls -l content
  artifacts:
    paths:
      - site/content
  only:
    - master

pages:
  image: registry.gitlab.com/pages/hugo:latest
  stage: page_deploy
  environment: production
  script:
    - hugo version
    - cd site
    - ls -lR content
    - hugo -c content -v
    - ls -l ../public
  artifacts:
    paths:
      - public
  only:
    - master
