variables:
  CXX: "g++ -std=c++17 -O3 -march=native -Wall -Wextra -I./include"

stages:
  - cpp_test
  - py_build
  - py_test

ReplayBuffer.cpp:
  image: gcc
  stage: cpp_test
  script:
    - g++ --version
    - $CXX -o test/ReplayBuffer test/ReplayBuffer.cpp
    - test/ReplayBuffer

SegmentTree.cpp:
  image: gcc
  stage: cpp_test
  script:
    - g++ --version
    - $CXX -o test/SegmentTree test/SegmentTree.cpp
    - test/SegmentTree
    
py_build:
  image: python
  stage: py_build
  script:
    - python --version
    - g++ --version
    - pip install cython
    - CC=g++ python setup.py build_ext --inplace
  artifacts:
    paths:
      - "*.so"

ReplayBuffer:
  stage: py_test
  script:
    - python -c "import ReplayBuffer"

SegmentTree:
  stage: py_test
  script:
    - python -c "import SegmentTree"
