variables:
  CXX: "g++ -std=c++17 -O3 -march=native -Wall -Wextra -Icpprb -pthread"
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - page_export
  - cpp_test
  - py_build
  - page_deploy
  - py_test

.job_template: &setup
  image: &dev_image registry.gitlab.com/ymd_h/cpprb/build:latest
  before_script:
    - g++ --version
    - python3 --version

.test_template: &py_setup
  image: *dev_image
  stage: py_test
  before_script:
    - g++ --version
    - python3 --version
    - pip install $(echo dist/cpprb-*)['all']
    - cd test

ReplayBuffer.cpp:
  <<: *setup
  stage: cpp_test
  script:
    - $CXX -o test/ReplayBuffer test/ReplayBuffer.cpp
    - test/ReplayBuffer

SegmentTree.cpp:
  <<: *setup
  stage: cpp_test
  script:
    - $CXX -o test/SegmentTree test/SegmentTree.cpp
    - test/SegmentTree

py_build:
  <<: *setup
  stage: py_build
  script:
    - CC=g++ python3 setup.py bdist_wheel
  artifacts:
    paths:
      - dist

ReplayBuffer:
  <<: *py_setup
  script:
    - python3 PyReplayBuffer.py

issue:
  <<: *py_setup
  script:
    - python3 issue.py

multi_rew:
  <<: *py_setup
  script:
    - python3 multi_rew.py

gym:
  <<: *py_setup
  script:
    - python3 gym.py

emacs:
  image: iquiw/alpine-emacs
  stage: page_export
  script:
    - emacs --version
    - emacs --batch README.org -l site/init.el --eval '(org-hugo-export-wim-to-md :all-subtrees nil t)'
    - cd site
    - emacs --batch site.org -l init.el --eval '(org-hugo-export-wim-to-md :all-subtrees nil t)'
    - ls -l content
  artifacts:
    paths:
      - site/content
  only:
    - master

pages:
  image: registry.gitlab.com/pages/hugo:latest
  stage: page_deploy
  environment: production
  script:
    - hugo version
    - cd site
    - ls -lR content
    - hugo -c content -v
    - ls -l ../public
  artifacts:
    paths:
      - public
  only:
    - master

sphinx:
  image: *dev_image
  stage: page_deploy
  environment: test
  script:
    - pip install $(echo dist/cpprb-*)['all']
    - mkdir test
    - sphinx-build -b html contents test
    - mv _build/html/ test/
  artifacts:
    paths:
      - test

