image: python

stages:
  - build
  - test

before_script:
  - pip install cython

build:
  stage: build
  script:
    - python setup.py build_ext --inplace
  artifacts:
    paths:
      - *.so

ReplayBuffer:
  stage: test
  script:
    - python -c "import ReplayBuffer"
