variables:
  CXX: "g++ -std=c++17 -O3 -march=native -Wall -Wextra -Icpprb -pthread"
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - page_export
  - page_deploy
  - cpp_test
  - py_build
  - py_test

ReplayBuffer.cpp:
  image: registry.gitlab.com/ymd_h/cpprb/build:latest
  stage: cpp_test
  script:
    - g++ --version
    - python3 --version
    - $CXX -o test/ReplayBuffer test/ReplayBuffer.cpp
    - test/ReplayBuffer
  when: always

SegmentTree.cpp:
  image: registry.gitlab.com/ymd_h/cpprb/build:latest
  stage: cpp_test
  script:
    - g++ --version
    - python3 --version
    - $CXX -o test/SegmentTree test/SegmentTree.cpp
    - test/SegmentTree

py_build:
  image: registry.gitlab.com/ymd_h/cpprb/build:latest
  stage: py_build
  script:
    - g++ --version
    - python3 --version
    - CC=g++ python3 setup.py build_ext
  artifacts:
    paths:
      - build

ReplayBuffer:
  image: registry.gitlab.com/ymd_h/cpprb/build:latest
  stage: py_test
  script:
    - g++ --version
    - python3 --version
    - python3 setup.py install
    - cd test
    - python3 PyReplayBuffer.py

emacs:
  image: iquiw/alpine-emacs
  stage: page_export
  script:
    - emacs --version
    - emacs --batch site.org -l init.el --eval '(org-hugo-export-wim-to-md :all-subtrees nil t)'
  artifacts:
    paths:
      - content
  only:
    - master

pages:
  image: registry.gitlab.com/pages/hugo:latest
  stage: page_deploy
  environment: production
  script:
    - ls -lR content
    - hugo version
    - hugo
  artifacts:
    paths:
      - public
  only:
    - master

