image: yamada4docker/gcc8_python372

variables:
  CXX: "g++ -std=c++17 -O3 -march=native -Wall -Wextra -I./include"

before_script:
  - g++ --version
  - python3 --version

stages:
  - cpp_test
  - py_build
  - py_test

ReplayBuffer.cpp:
  stage: cpp_test
  script:
    - $CXX -o test/ReplayBuffer test/ReplayBuffer.cpp
    - test/ReplayBuffer

SegmentTree.cpp:
  stage: cpp_test
  script:
    - $CXX -o test/SegmentTree test/SegmentTree.cpp
    - test/SegmentTree

py_build:
  stage: py_build
  script:
    - pip3 install cython
    - CC=g++ python3 setup.py build_ext --inplace
  artifacts:
    paths:
      - "*.so"

ReplayBuffer:
  stage: py_test
  script:
    - python3 -c "import ReplayBuffer"

SegmentTree:
  stage: py_test
  script:
    - pip3 install cython
    - python3 setup.py install
    - python3 -c test/SegmentTree.py
