stages:
  - cpp_test
  - py_build
  - py_test

ReplayBuffer.cpp:
  image: gcc
  stage: cpp_test
  script:
    - g++ --version
    - g++ -std=c++17 -O3 -march=native -Wall -Wextra -I./ReplayBuffer -o test/ReplayBuffer test/ReplayBuffer.cpp
    - test/ReplayBuffer

SegmentTree.cpp:
  image: gcc
  stage: cpp_test
  script:
    - g++ --version
    - g++ -std=c++17 -O3 -march=native -Wall -Wextra -I./SegmentTree -o test/SegmentTree test/SegmentTree.cpp
    
py_build:
  image: python
  stage: py_build
  script:
    - pip install cython
    - python setup.py build_ext --inplace
  artifacts:
    paths:
      - "*.so"

ReplayBuffer:
  stage: py_test
  script:
    - python -c "import ReplayBuffer"

SegmentTree:
  stage: py_test
  script:
    - python -c "import SegmentTree"
