image: registry.gitlab.com/ymd_h/cpprb/build:latest

variables:
  CXX: "g++ -std=c++17 -O3 -march=native -Wall -Wextra -Icpprb"

before_script:
  - g++ --version
  - python3 --version

stages:
  - cpp_test
  - py_build
  - py_test

ReplayBuffer.cpp:
  stage: cpp_test
  script:
    - $CXX -o test/ReplayBuffer test/ReplayBuffer.cpp
    - test/ReplayBuffer

SegmentTree.cpp:
  stage: cpp_test
  script:
    - $CXX -o test/SegmentTree test/SegmentTree.cpp
    - test/SegmentTree

py_build:
  stage: py_build
  script:
    - CC=g++ python3 setup.py build_ext
  artifacts:
    paths:
      - build

ReplayBuffer:
  stage: py_test
  script:
    - python3 setup.py install
    - cd test
    - python3 PyReplayBuffer.py
