baseURL = "https://ymd_h.gitlab.io/cpprb/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "cpprb"
theme = "learn"
themesdir = "themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true
publishDir = "../public"

[params]
  description = "Site for cpprb"
  author = "Hiroyuki Yamada"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = true
  themeVariant = "cpprb"
  disableInlineCopyToClipBoard = true
  images = "/cpprb/images/logo.png"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-gitlab'></i> GitLab"
identifier = "ds"
url = "https://gitlab.com/ymd_h/cpprb"
weight = 10

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub Mirror"
identifier = "gh"
url = "https://github.com/ymd-h/cpprb"
weight = 15

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Class Reference"
identifier = "api"
url = "https://ymd_h.gitlab.io/cpprb/api/"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-comments'></i> User Forum"
identifier = "forum"
url = "https://github.com/ymd-h/cpprb/discussions"
weight = 25

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-bug'></i> Unit Test Coverage"
identifier = "cov"
url = "https://ymd_h.gitlab.io/cpprb/coverage/"
weight = 30


[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-blog'></i> Author's Blog"
identifier = "blg"
url = "https://ymd_h.gitlab.io/ymd_blog/"
weight = 40
