baseURL = "https://ymd_h.gitlab.io/cpprb/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "C++ Replay Buffer"
theme = "learn"
themesdir = "themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true
publishDir = "../public"

[params]
  editURL = "https://gitlab.com/ymd_h/cpprb/edit/master/content/"
  description = "Site for cpprb (C++ Replay Buffer)"
  author = "Hiroyuki Yamada"
  showVisitedLinks = false
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "blue"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-gitlab'></i> Gitlab repo"
identifier = "ds"
url = "https://gitlab.com/ymd_h/cpprb"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> Class Reference"
identifier = "api"
url = "https://ymd.gitlab.io/cpprb/api/"
weight = 20