name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with: python-version: '3.7'
      - run: pip install cython setuptools
      - run: pip install '.[gym]'
      - run: python -m unittest discover . '*.py'
        working-directory: './test'
