name: CI

on: [push]

jobs:
  readme:
    container: iquiw/alpine-emacs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: emacs --batch README.org --eval '(org-md-export-to-markdown)'
      - uses: actions/upload-artifact@v1
        with:
          name: README
          path: README.md
  build:
    needs: readme
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
        python: ['3.6', '3.7', '3.8', '3.9']
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Get pip cache dir
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"
      - name: pip cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip${{ matrix.python }}
          restore-keys: ${{ runner.os }}-pip${{ matrix.python }}
      - run: pip install wheel
      - run: pip install cython setuptools twine gym 'numpy<1.20.0'
      - name: Install cpprb
        run: pip install '.[gym]'
      - run: python -m unittest discover . '*.py'
        working-directory: './test'
      - uses: actions/download-artifact@v1
        with:
          name: README
      - run: mv README/README.md README.md
      - run: python setup.py bdist_wheel
        if: startsWith(runner.os, 'Windows')
      - uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
        if: startsWith(runner.os, 'Windows')
      - name: Upload to PyPI
        run: python -m twine upload -u __token__ -p ${{ secrets.pypi_password }} --skip-existing dist/cpprb-*
        if: github.event_name == 'push' && startsWith(github.event.ref,'refs/tags/v') && startsWith(runner.os, 'Windows')
        continue-on-error: true
  build_aarch64:
    needs: readme
    runs-on: ubuntu-latest
    env:
      img: quay.io/pypa/manylinux2010_aarch64
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64
      - uses: actions/download-artifact@v1
        with:
          name: README
      - run: mv README/README.md README.md
      - run: |
          docker run -v $(pwd):/cpprb ${img} bash -c 'for PIP in /opt/python/cp3{6m,7m,8,9}/bin/pip; do ${PIP} install "numpy<1.20.0" && ${PIP} wheel /cpprb -w /cpprb/wheelhouse/ --no-deps; done'
      - run: |
          docker run -v $(pwd):/cpprb ${img} bash -c 'for WHL in /cpprb/wheelhouse/cpprb-*.whl; do auditwheel repair ${WHL} -w /cpprb/dist; done'
      - uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
      - run: pip install twine
      - name: Upload to PyPI
        run: python -m twine upload -u __token__ -p ${{ secrets.pypi_password }} --skip-existing dist/cpprb-*
        if: github.event_name == 'push' && startsWith(github.event.ref,'refs/tags/v')
