name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@master
      - run: pip3 install cython setuptools
      - run: pip3 install .
